server:
  port: 8761



bank:
  serviceRegistry:
    username: serviceregistry
    password: ${PASSWORD}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: 'http://${bank.serviceRegistry.username}:${PASSWORD}@localhost:8761/eureka'

